version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - antfu
  - Astro
  - Attributify
  - bumpp
  - codemirror
  - collab
  - easytag
  - emittypes
  - iconify
  - lezer
  - Logseq
  - nolebase
  - Nólëbase
  - ofetch
  - tailwindcss
  - unocss
  - vueuse
  - Astro
  - Attributify
  - preflights
  - easytag
  - emittypes
  - Logseq
  - preflights
ignoreWords: []
import: []
